### PR TITLE
refactor: return raw bytes from iterator

### PR DESCRIPTION
**Pull request by tomkarw**
BREAKING CHANGE: changes the return type of the iterator from String to Result<Vec<u8>, io::Error>

### CODE REVIEW

**Comment by tomkarw** [comment]
No idea why the test with invalid utf-8 fails. Seems like it doesn't read the newline at the end of the invalid bytes (or there is no newline? I can only see `13` which would be `CR`).

Funny enough, when I opened the file in editor and edited it, once saved, the file changes and the newline is present and test passes as expected. I could have left it like that, but I want to make sure we know why the `it_handles_file_with_invalid_utf8` fails as-is.

**Comment by tomkarw** [comment]
Yeah, so the test was confusing, because inspecting files with invalid utf-8 is hard. It worked correctly, as there was only one newline in there.

I refactored tests to use a `Cursor` of inlined data instead, this way there's no need to store any files, you see the input right in the test, and it's *way* easier to represent non-utf8 characters.

**Comment by tomkarw** [comment]
I'll have two more proposals.

One is about performance, I think there are some optimizations about how the vector returned from the iterator is constructed (instead of multiple pushes and a reverse, we can build the vector up from chunks). This would also require benchmarking to validate, so I'd add these as a bonus.

I looked at how [lines](https://doc.rust-lang.org/std/io/trait.BufRead.html#method.lines) is implemented in std, and they actually return `Result<String>`, so they try the conversion for the user. Maybe we could provide two iterators `RevLines` which yields `Result<String>` and `RawRevLines` which yields `Result<Vec<u8>>`?

**Comment by mjc-gh** [comment]
Sorry for the slow response, got very busy with other stuff the last week or so.

> I looked at how [lines](https://doc.rust-lang.org/std/io/trait.BufRead.html#method.lines) is implemented in std, and they actually return Result<String>, so they try the conversion for the user. Maybe we could provide two iterators RevLines which yields Result<String> and RawRevLines which yields Result<Vec<u8>>?

This sounds like a good idea to me and would offer the most flexibility overall. Happy to include these changes in a v1.0 release if you'd like to make another PR for it.

**Pull request merged**
