### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by tomkarw**
Depends on https://github.com/mjc-gh/rev_lines/pull/8 for handling non-utf8 lines.

* style: run rustfmt
* refactor: apply clippy sugestions
* feat: don't require wrapping Reader into BufReader by API user (breaking change, better API)
* refactor: infallible constructor, return Results from iterator (lazy new is more idiomatic, don't panic on IO read issues)

### CODE REVIEW

**Comment by mjc-gh** [comment]
Thanks for the contributions @tomkarw. There were some UTF changes merged in on another PR. I also ran `fmt` and `clippy` changes myself (which was long overdue) and published a 0.2.2 version.

There's some conflicts now with this PR. I'm not sure I see exactly what `RevByteLines` does though, could you explain that a bit? I'm also a little torn on the constructor changes. I understand not returning possible error results makes for an easier API to use but it does crate a breaking change.

I'm hoping to publish a 1.0 version sooner than later for this package which could allow for breaking API changes then.

**Comment by tomkarw** [comment]
I can extract the relevant changes into separate PRs. There are basically 4 proposals:

1. reading from the file is a fallible operation, the iterator should not hide the errors, and thus return `io::Results`
2. we need to deal with files that are not valid utf-8:
  *  one possibility is to try to do the conversion for the user, and return an error from the iterator, so now there would be a need to add a custom error type, as there could be a failure to read (returning something like `RevLinesError::Io(io::Error)`), or to parse bytes (returning `RevLinesError::Utf8Error(str::Utf8Error)`)
  * however, there are different strategies to deal with the bytes, one can do `String::from_utf8_lossy`, or `String::from_utf8_unchecked` if they dare. Point is, it's better to just return the raw bytes, and let the end user decide which strategy to choose. So just return `Vec<u8>` where you return `String` today
3. Rust has this neat approach of lazy constructors. Basically, the least amount of work should happen in the `new` call, in case we create the value but never use it. So I moved the preprocessing (moving the cursor before the last newline) to the first call of `next`. This has the added benefit that now the constructor is infallible.
4. The fact that `BufReader` is used is an implementation detail, so it's more convenient for user to just pass anything that's `Read + Seek`

**Comment by mjc-gh** [comment]
Appreciate this write up, very helpful!

> 1. reading from the file is a fallible operation, the iterator should not hide the errors, and thus return `io::Results`

Happy to merge this change and we can eventually do a v1.0 release with it since it'll change the API.

> 2. we need to deal with files that are not valid utf-8:

I think the second route seems more robust overall by returning a `Vec<u8>`. This should result in a simpler API overall as well, which is a win win.

> 3. Rust has this neat approach of lazy constructors. Basically, the least amount of work should happen in the new call, in case we create the value but never use it. So I moved the preprocessing (moving the cursor before the last newline) to the first call of next. This has the added benefit that now the constructor is infallible.

This seems very reasonable and good change overall. Since this goes with #1, the v1.0 release will cover the API changes

> 4. The fact that BufReader is used is an implementation detail, so it's more convenient for user to just pass anything that's Read + Seek

Really like this change and it once again makes this package more robust overall. Really appreciate the contributions and am happy to merge PRs tomorrow and try to cut a v1.0 release then. Thanks again!

**Comment by tomkarw** [comment]
Hey, I should have some time this week to work on this. Don't lose hope 😅

**Pull request closed without merging**
