### PR TITLE
ci: add benchmark to ci

### PR DESCRIPTION
**Pull request by tomkarw**

### CODE REVIEW

**Comment by tomkarw** [comment]
@mjc-gh Still fails, but only here.

In my fork it worked: https://github.com/tomkarw/rev_lines/actions/runs/5299453339/jobs/9592419705. This is how the result looks: https://github.com/tomkarw/rev_lines/commit/9911e610283a65fa6902191e7dfeb6bf8c443d14#commitcomment-118526673.

This is the workflow permissions that I've set there:
image

**Comment by tomkarw** [comment]
Added a direct PR comment as well, that's how it looks like: https://github.com/tomkarw/rev_lines/pull/1#issuecomment-1595842769

**Comment by mjc-gh** [comment]
image

I think I have that setting already set to read and write. Not sure what else I am missing, let me know if anything seems incorrect on this settings page screenshot.

Maybe we need to add [`permissions`](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) to the benchmark job? Something like `permissions: write-all` or even this for more limited ones: 

```yaml
permissions:
  discussions: write
```

Seems odd it would work fine on your fork but not here though. Maybe I have some read only by default setting set elsewhere?

**Comment by tomkarw** [comment]
> Seems odd it would work fine on your fork but not here though. Maybe I have some read only by default setting set elsewhere?

Damn, I'm so disappointed with GitHub. The reason the workflow is failing here, is that PR from forks **only have read permissions and cannot be bumped in any way** (https://github.com/orgs/community/discussions/36778#discussioncomment-4051149). 1) The error could be much clearer, giving this exact reasoning, and 2) it means we cannot do it the way I wanted :cry:. The commit comment on merging to main will work (as it will be triggered by you in the repo you own), but there's no clear way to add nice PR comments during CR.

**Comment by mjc-gh** [comment]
That is unfortunate and the error and repo settings are not very clear. Will merge this now and at least we'll get these benchmark comments on main merges.

**Comment by tomkarw** [comment]
Hmm, I don't think it was right to merge this. Any pipeline on following PR will fail now. Additionally, I didn't mention that, but there was an issue that the commit comment now always compares `main` branch to the branch that triggered the action, so also `main`, always giving `no change` result.

**Comment by mjc-gh** [comment]
> Hmm, I don't think it was right to merge this. Any pipeline on following PR will fail now. Additionally, I didn't mention that, but there was an issue that the commit comment now always compares main branch to the branch that triggered the action, so also main, always giving no change result.

Gotcha, I thought with it only being for main, it would run when the PR was merged and write a comment then. We can revert this.

**Pull request merged**
